# Generated by Django 3.1.4 on 2021-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0002_auto_20210724_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default='Enter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
