# Generated by Django 3.1.4 on 2021-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0003_auto_20210726_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
