# Generated by Django 3.1.4 on 2021-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0004_auto_20210726_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
