# Generated by Django 3.1.4 on 2021-07-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0005_auto_20210726_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='date',
        ),
    ]
