# Generated by Django 3.1.4 on 2021-07-26 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0006_remove_news_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
