# Generated by Django 3.1.4 on 2021-07-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexus_360', '0007_news_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='post_date',
        ),
    ]
